### ISSUE TITLE
"'pip' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by Fallde** [csjh/SkyblockSniper#1]
I have no idea on how to fix this.

**Comment by csjh** [comment]
That means you didn't properly add Python and Python's scripts to your system PATH variables.

Refer to [https://datatofish.com/add-python-to-windows-path/](https://datatofish.com/add-python-to-windows-path/)

**Comment by Fallde** [comment]
i fixed the pip issue but now when i type pip install -r (directory) it says "ERROR: Could not open requirements file: [Errno 13] Permission denied: '(directory)"

**Comment by csjh** [comment]
> i fixed the pip issue but now when i type pip install -r (directory) it says "ERROR: Could not open requirements file: [Errno 13] Permission denied: '(directory)"

Are you including requirements.txt in the path?

**Comment by Fallde** [comment]
ok i fixed that but now ANOTHER problem... "Looking for auctions...
Traceback (most recent call last):
  File "C:\Users\****\Downloads\SkyblockSniper.py", line 105, in <module>
    main()
  File "C:\Users\****\Downloads\SkyblockSniper.py", line 88, in main
    loop.run_until_complete(future)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\****\Downloads\SkyblockSniper.py", line 75, in get_data_asynchronous
    for response in await asyncio.gather(*tasks):
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\****\Downloads\SkyblockSniper.py", line 55, in fetch
    if prices[index][1] > LOWEST_PRICE and prices[index][0] < prices[index][1]/2 and auction['start']+60000 > now:
TypeError: '>' not supported between instances of 'float' and 'tuple'"

**Comment by Fallde** [comment]
Ok nvm i fixed it. i hadnt changed the value to 5 before hand. tysm for the help man. best of luck in the future.
